import { Application } from '@/types';

// Helper to create dates relative to now
const daysAgo = (days: number): Date => {
    const date = new Date();
    date.setDate(date.getDate() - days);
    return date;
};

export const mockApplications: Application[] = [
    {
        id: '550e8400-e29b-41d4-a716-446655440001',
        userId: 'user-001',
        companyName: 'Google',
        jobTitle: 'Senior Software Engineer',
        jobUrl: 'https://careers.google.com/jobs/123',
        location: 'Mountain View, CA',
        remotePolicy: 'Hybrid',
        status: 'APPLIED',
        priority: 'HIGH',
        jobType: 'FULL_TIME',
        appliedDate: daysAgo(5),
        salaryMin: 1800000,
        salaryMax: 2500000,
        currency: 'INR',
        createdAt: daysAgo(7),
        updatedAt: daysAgo(5),
    },
    {
        id: '550e8400-e29b-41d4-a716-446655440002',
        userId: 'user-001',
        companyName: 'Stripe',
        jobTitle: 'Full Stack Developer',
        jobUrl: 'https://stripe.com/jobs/456',
        location: 'San Francisco, CA',
        remotePolicy: 'Remote',
        status: 'INTERVIEW_SCHEDULED',
        priority: 'HIGH',
        jobType: 'FULL_TIME',
        appliedDate: daysAgo(14),
        salaryMin: 1600000,
        salaryMax: 2200000,
        currency: 'INR',
        createdAt: daysAgo(20),
        updatedAt: daysAgo(3),
    },
    {
        id: '550e8400-e29b-41d4-a716-446655440003',
        userId: 'user-001',
        companyName: 'Notion',
        jobTitle: 'Frontend Engineer',
        jobUrl: 'https://notion.so/careers/789',
        location: 'New York, NY',
        remotePolicy: 'Hybrid',
        status: 'WISHLIST',
        priority: 'MEDIUM',
        jobType: 'FULL_TIME',
        appliedDate: undefined,
        salaryMin: 1500000,
        salaryMax: 2000000,
        currency: 'INR',
        createdAt: daysAgo(2),
        updatedAt: daysAgo(2),
    },
    {
        id: '550e8400-e29b-41d4-a716-446655440004',
        userId: 'user-001',
        companyName: 'Razorpay',
        jobTitle: 'Backend Engineer',
        jobUrl: 'https://razorpay.com/careers',
        location: 'Bangalore, India',
        remotePolicy: 'Hybrid',
        status: 'OA_RECEIVED',
        priority: 'MEDIUM',
        jobType: 'FULL_TIME',
        appliedDate: daysAgo(10),
        salaryMin: 2000000,
        salaryMax: 3500000,
        currency: 'INR',
        createdAt: daysAgo(12),
        updatedAt: daysAgo(1),
    },
    {
        id: '550e8400-e29b-41d4-a716-446655440005',
        userId: 'user-001',
        companyName: 'Flipkart',
        jobTitle: 'SDE Intern',
        jobUrl: 'https://flipkart.com/careers',
        location: 'Bangalore, India',
        remotePolicy: 'On-site',
        status: 'OFFER',
        priority: 'HIGH',
        jobType: 'INTERNSHIP',
        appliedDate: daysAgo(30),
        salaryMin: 50000,
        salaryMax: 80000,
        currency: 'INR',
        createdAt: daysAgo(35),
        updatedAt: daysAgo(0),
    },
];
